#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 21 19:38:32 2019

@author: aidasaglinskas
"""

# https://www.youtube.com/watch?v=cXHvC_FGx24
import numpy as np
from scipy.optimize import minimize  

def objective(x):
    x1 = x[0]
    x2 = x[1]
    x3 = x[2]
    x4 = x[3]

    return x1*x4*(x1+x2+x3)+x3

def constraint1(x):
    return x[0]*x[1]*x[2]*x[3]-25.

def constraint2(x):
    sum_sq = 40
    for i in range(4):
        sum_sq = sum_sq - x[i]**2
    
    return x[0]*x[1]*x[2]*x[3]-25.
 

#x0 = np.zeros(4)aa
#%%
x0 = [0,0,0,0]
print(objective(x0))

b = (1.0,5.0)
bnds = (b,b,b,b)
con1 = {'type' : 'ineq', 'fun' : constraint1}
con2 = {'type' : 'ineq', 'fun' : constraint2}
cons = [con1,con2]
sol = minimize(objective,x0,method='SLSQP',bounds=bnds,constraints=cons)

minimize(objective,x0,method='SLSQP',bounds=bnds,constraints=cons)
print(sol.fun)
print(sol.x)